#pragma config(Motor,  port2,           back,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           front,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEADBAND 10

struct MotorValues {
	int front;
	int back;
	int left;
	int right;
};
task main()
{
	//motor to access motor powers
	//vexRT to access remote values
	//SensorValue to access sensors
	//Ch1 left-right on the right joystick
	//Ch2 up-down on the right joystick
	//Ch3 up-down on the left joystick
	//Ch4 left-right on the left joystick
	while (true)
	{
		int upDownLeftJoystick = vexRT[Ch3];
		int leftRightLeftJoystick = vexRT[Ch4];
		int upDownRightJoystick = vexRT[Ch2];
		int leftRightRightJoystick = vexRT[Ch1];
		struct MotorValues motors;

		if (abs(upDownLeftJoystick) > DEADBAND) // If the left joystick is greater than or less than the threshold, go that direction. (right motor is reversed)
		{
			motors.left = upDownLeftJoystick;
			motors.right = -upDownLeftJoystick;
		}
		if (abs(leftRightLeftJoystick) > DEADBAND) // If the left joystick is greater than or less than the threshold, go that direction. (back motor is reversed)
		{
			motors.front = leftRightLeftJoystick;
			motors.back = -leftRightLeftJoystick;
		}
		if (abs(leftRightRightJoystick) > DEADBAND) // If the right joystick is greater than or less than the threshold then spin in that direction.
		{
			motors.front = leftRightRightJoystick;
			motors.left = leftRightRightJoystick;
			motors.back = leftRightRightJoystick;
			motors.right = leftRightRightJoystick;
		}

		motor[back] = backMotorPower;
		motor[front] = frontMotorPower;
		motor[left] = leftMotorPower;
		motor[right] = rightMotorPower;
	}
}
