#pragma config(Motor,  port2,           back,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           front,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEADBAND 10

struct MotorValues {
	int front;
	int back;
	int left;
	int right;
};

struct JoystickValues {
	int upDown;
	int leftRight;
};

struct Joysticks {
	struct JoystickValues left;
	struct JoystickValues right;
};

void setMotorPower(struct MotorValues &motors) {
	motor[back] = motors.back;
	motor[front] = motors.front;
	motor[left] = motors.left;
	motor[right] = motors.right;
}

void initJoysticks(struct Joysticks &js) {
	js.left.upDown = vexRT[Ch3];
	js.left.leftRight = vexRT[Ch4];
	js.right.upDown = vexRT[Ch2];
	js.right.leftRight = vexRT[Ch1];
}

void moveLeftRight(struct Joysticks &js, struct MotorValues &motors) {
	if (abs(js.left.upDown) > DEADBAND) // If the left joystick is greater than or less than the threshold, go that direction. (right motor is reversed)
	{
		motors.left = js.left.upDown;
		motors.right = -js.left.upDown;
	}
}

task main()
{
	//motor to access motor powers
	//vexRT to access remote values
	//SensorValue to access sensors
	//Ch1 left-right on the right joystick
	//Ch2 up-down on the right joystick
	//Ch3 up-down on the left joystick
	//Ch4 left-right on the left joystick
	while (true)
	{
		struct Joysticks js;
		initJoysticks(js);
		struct MotorValues motors;

		moveLeftRight(js, motors);
		if (abs(js.left.leftRight) > DEADBAND) // If the left joystick is greater than or less than the threshold, go that direction. (back motor is reversed)
		{
			motors.front = js.left.leftRight;
			motors.back = -js.left.leftRight;
		}
		if (abs(js.right.leftRight) > DEADBAND) // If the right joystick is greater than or less than the threshold then spin in that direction.
		{
			motors.front = js.right.leftRight;
			motors.left = js.right.leftRight;
			motors.back = js.right.leftRight;
			motors.right = js.right.leftRight;
		}

		setMotorPower(motors);
	}
}
