#pragma config(Motor,  port2,           back,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           front,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEADBAND 10

task main()
{
	while (true)
	{
		int upDownLeftJoystick = vexRT[Ch3];
		int leftRightLeftJoystick = vexRT[Ch4];
		int upDownRightJoystick = vexRT[Ch2];
		int leftRightRightJoystick = vexRT[Ch1];
		int frontMotorPower = 0, backMotorPower = 0, leftMotorPower = 0, rightMotorPower = 0;

		{
			leftMotorPower = upDownLeftJoystick;
			rightMotorPower = -upDownLeftJoystick;
		}
		{
			frontMotorPower = leftRightLeftJoystick;
			backMotorPower = -leftRightLeftJoystick;
		}


		motor[back] = backMotorPower;
		motor[front] = frontMotorPower;
		motor[left] = leftMotorPower;
		motor[right] = rightMotorPower;
	}
}
